import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const siteDataPath = path.join(root, "site", "data.js");
const readmePath = path.join(root, "README.md");

function parseSiteData() {
  const raw = readFileSync(siteDataPath, "utf8").trim();
  const prefix = "window.IMAGE_KB = ";
  if (!raw.startsWith(prefix)) {
    throw new Error("site/data.js is not in the expected format.");
  }
  return JSON.parse(raw.slice(prefix.length).replace(/;\s*$/, ""));
}

function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function repoPath(value) {
  return String(value ?? "").replace(/^\.\.\//, "");
}

function toRows(items, columns) {
  const rows = [];
  for (let index = 0; index < items.length; index += columns) {
    rows.push(items.slice(index, index + columns));
  }
  return rows;
}

function buildGalleryTable(images) {
  if (!images.length) return "_No public images yet._";
  const rows = toRows(images, 2);
  return [
    "<table>",
    ...rows.map((row) => {
      const cells = row
        .map((image) => {
          const label = `${image.title} (${image.taxonomy})`;
          const hooks = (image.specificHooks ?? []).slice(0, 2).join(" · ");
          return [
            "<td width=\"50%\" align=\"center\" valign=\"top\">",
            `  <a href="${escapeHtml(repoPath(image.promptPath))}"><img src="${escapeHtml(repoPath(image.pngPath))}" alt="${escapeHtml(label)}" width="100%" /></a>`,
            `  <br /><strong>${escapeHtml(image.title)}</strong>`,
            `  <br /><sub>${escapeHtml(image.taxonomy)} · ${escapeHtml(hooks)}</sub>`,
            "</td>",
          ].join("\n");
        })
        .join("\n");
      return `<tr>\n${cells}\n</tr>`;
    }),
    "</table>",
  ].join("\n");
}

function buildTaskTable(images) {
  const rows = images.slice(0, 6).map((image) => {
    const task = (image.learningValue ?? image.runTheme ?? "").split(".")[0] || image.title;
    const hooks = (image.specificHooks ?? []).slice(0, 3).join(", ");
    return `| ${image.title} | ${task} | ${hooks} |`;
  });
  return [
    "| Panel | Human task | Labels |",
    "| --- | --- | --- |",
    ...rows,
  ].join("\n");
}

const data = parseSiteData();
const publicImages = [...(data.images ?? [])]
  .filter((image) => image.curation?.status !== "archived")
  .sort((a, b) => (b.rubric?.total ?? 0) - (a.rubric?.total ?? 0) || (b.timestamp ?? "").localeCompare(a.timestamp ?? ""));
const publicRuns = [...(data.runs ?? [])]
  .filter((run) => run.publicImageCount > 0)
  .sort((a, b) => (b.timestamp ?? "").localeCompare(a.timestamp ?? ""));
const hero = publicImages[0] ?? null;
const recentRun = publicRuns[0] ?? null;
const formats = new Set(publicImages.map((image) => image.taxonomy)).size;
const hooks = data.hooks?.length ?? 0;

const readme = `<!-- Generated by scripts/build-readme.mjs. -->

# Image Atlas

> A public, image-first slice of a labeled PNG atlas built for practical human tasks, explainer plates, and searchable visual reference work.

${hero ? `[![${hero.title}](${repoPath(hero.pngPath)})](${repoPath(hero.promptPath)})` : ""}

| Public images | Public runs | Search hooks | Formats |
| --- | --- | --- | --- |
| ${publicImages.length} | ${publicRuns.length} | ${hooks} | ${formats} |

## What This Repo Publishes

- Useful labeled image runs instead of generic art dumps.
- Matching prompt cards, research notes, run reports, and static gallery pages for every published PNG.
- A curated public mirror of the larger working atlas, kept small enough for normal GitHub pushes.

## Current Public Gallery

${buildGalleryTable(publicImages)}

## Useful Human Tasks In This Seed

${buildTaskTable(publicImages)}

## Current Seed Run

${recentRun ? `- **Theme:** ${recentRun.theme}` : "- **Theme:** No public run yet."}
${recentRun ? `\n- **Coverage:** ${recentRun.publicImageCount} panels with prompt cards and a run report.` : ""}
${recentRun ? `\n- **Run page:** [${recentRun.slug}](site/r/${recentRun.slug}/index.html)` : ""}

## Publish Automation

1. Sync the newest useful run from the working atlas into this public repo:
   \`node scripts/sync-public-atlas.mjs --source ../image-knowledge-base\`
2. Rebuild the gallery data and generated README, then commit and push:
   \`./scripts/run-public-sync.sh ../image-knowledge-base\`
3. Install the local launchd watcher for continuous GitHub publishing:
   \`./scripts/install-launch-agent.sh ../image-knowledge-base\`

### Volume Profile

- Default public sync now targets \`10+\` images per run and publishes up to \`3\` new runs per cycle.
- Set \`IMAGE_ATLAS_PUBLIC_MAX_NEW_RUNS=0\` to allow unlimited new runs in one sync.
- Set \`IMAGE_ATLAS_PUBLIC_MAX_NEW_IMAGES=200\` to cap one publish pass by image count instead of run count.
- Set \`IMAGE_ATLAS_PUBLIC_SYNC_INTERVAL_SECONDS=300\` before installing the launch agent to publish every 5 minutes.
- Set \`IMAGE_ATLAS_PUBLIC_MIN_IMAGES_PER_RUN=10\` to keep the public mirror focused on substantial batches.

Example high-volume install:

\`\`\`bash
IMAGE_ATLAS_PUBLIC_MAX_NEW_RUNS=5 \\
IMAGE_ATLAS_PUBLIC_MAX_NEW_IMAGES=120 \\
IMAGE_ATLAS_PUBLIC_MIN_IMAGES_PER_RUN=10 \\
IMAGE_ATLAS_PUBLIC_SYNC_INTERVAL_SECONDS=300 \\
./scripts/install-launch-agent.sh ../image-knowledge-base
\`\`\`

## Repo Layout

- \`images/\`: published PNGs, grouped by date and run slug.
- \`prompts/\`: one prompt card per image with searchable hooks and composition notes.
- \`research/\`: run research briefs and visual lessons.
- \`run-reports/\`: concise run-level summaries.
- \`catalog/\`: machine-readable JSONL records used to build the site and README.
- \`site/\`: static visual browser with per-image pages, run pages, sitemap, and robots file.
`;

writeFileSync(readmePath, readme);
console.log(`Wrote README for ${publicImages.length} public images across ${publicRuns.length} runs.`);
